sudo: false

language: python

python:
  - "3.4"

branches:
  only:
    - master


# install dependencies
install: "pip install -r dependencies.txt"

# create database
before_script:
  - "psql -c 'create database testdb'; -U postgres"

# run tests
script: "python tests.py"
