FORMAT: 1A

# StarLords
An API to access resources in our [Universe database] (https://github.com/sygmo/cs373-idb/)

# Group Constellation Resources
## Constellation Collection [/api/constellation]
A list of all Constellation objects
### List all Constellations [GET]
+ Response 200 (application/json)

        [{ 
            "id": 1, 
            "name": "Draco", 
            "stars_with_planets": 19, 
            "meaning": "dragon", 
            "fk_constellation_family": 3, 
            "history": "lies in the far northern sky. eighth-largest constellation", 
            "photo_link": "http://upload.wikimedia.org/wikipedia/commons/c/c3/DracoCC.jpg", 
            "photo": \000
        }, { 
            "id": 2, 
            "name": "Fornax", 
            "stars_with_planets": 7, 
            "meaning": "chemical furnace", 
            "fk_constellation_family": 4, 
            "history": "lies in the southern sky. is in the southern hemisphere", 
            "photo_link": "http://upload.wikimedia.org/wikipedia/commons/c/ce/Constellation_Fornax.jpg", 
            "photo": \001
        }]

## Constellation [/api/constellation/{id}]
A single Constellation object with all its details

+ Parameters
    + id (required, int, `1`) ... int `id` of the Constellation to perform action with. Has example value.

### Retrieve a Constellation [GET]
+ Response 200 (application/json)

    + Header

    + Body

            { 
                "id": 1, 
                "name": "Draco", 
                "stars_with_planets": 19, 
                "meaning": "dragon", 
                "fk_constellation_family": 3, 
                "history": "lies in the far northern sky. eighth-largest constellation", 
                "photo_link": "http://upload.wikimedia.org/wikipedia/commons/c/c3/DracoCC.jpg", 
                "photo": \000
            }

+ Response 404 (application/json)

    + Header

    + Body
    
            { 
                "error": "Sorry. That constellation doesn't exist."
            }

# Group Exoplanet Resources
## Exoplanet Collection [/api/exoplanet]
A list of all Exoplanet objects
### List all Exoplanets [GET]
+ Response 200 (application/json)

        [{ 
            "id": 1, 
            "name": "Kepler-107d", 
            "discovered": 2014, 
            "orbital_period": "7.95", 
            "semi_major_axis": 0.0780, 
            "discovery_method": "Transit", 
            "history": "discovered by the Kepler spacecraft", 
            "fk_star_planet": 2,
            "photo_link": "http://www.robotplanet.dk/astro/exoplanets/kepler-107_d.png",
            "photo": \000
        }, { 
            "id": 2, 
            "name": "WASP-14b", 
            "discovered": 2009, 
            "orbital_period": "2.24", 
            "semi_major_axis": 0.03677, 
            "discovery_method": "Transit", 
            "history": "one of the densest exoplanets known.", 
            "fk_star_planet": 4,
            "photo_link": "http://upload.wikimedia.org/wikipedia/en/thumb/1/15/Planet_WASP-14_b.png/250px-Planet_WASP-14_b.png",
            "photo": \001
        }]

## Exoplanet [/api/exoplanet/{id}]
A single Exoplanet object with all its details

+ Parameters
    + id (required, int, `1`) ... int `id` of the Exoplanet to perform action with. Has example value.

### Retrieve a Exoplanet [GET]
+ Response 200 (application/json)

    + Header

    + Body
    
            { 
                "id": 1, 
                "name": "Kepler-107d", 
                "discovered": 2014, 
                "orbital_period": "7.95", 
                "semi_major_axis": 0.0780, 
                "discovery_method": "Transit", 
                "history": "discovered by the Kepler spacecraft", 
                "fk_star_planet": 2,
                "photo_link": "http://www.robotplanet.dk/astro/exoplanets/kepler-107_d.png",
                "photo": \000
            }

+ Response 404 (application/json)

    + Header

    + Body
    
            { 
                "error": "Sorry. That Exoplanet doesn't exist."
            }

# Group Family Resources
## Family Collection [/api/family]
A list of all Family objects
### List all Families [GET]
+ Response 200 (application/json)

        [{ 
            "id": 1, 
            "name": "Ursa Major"
        }, { 
            "id": 2, 
            "name": "Zodiac"
        }]

## Family [/api/family/{id}]
A single Family object with all its details

+ Parameters
    + id (required, int, `1`) ... int `id` of the Family to perform action with. Has example value.

### Retrieve a Family [GET]
+ Response 200 (application/json)

    + Header

    + Body

            { 
                "id": 1, 
                "name": "Ursa Major"
            }

+ Response 404 (application/json)

    + Header

    + Body
    
            { 
                "error": "Sorry. That Family doesn't exist."
            }

# Group Moon Resources
## Moon Collection [/api/moon]
A list of all Moon objects
### List all Moons [GET]
+ Response 200 (application/json)

        [{ 
            "id": 1, 
            "name": "Phobos", 
            "radius": 11.26, 
            "volume": 5783.61, 
            "mass": 1.0659, 
            "distance_from_planet": 5826, 
            "orbital_period": .318, 
            "surface_gravity": 0.0057,
            "history": "named after the Greek god Phobos - the personfication of Horror", 
            "photo_link": "http://en.wikipedia.org/wiki/File:Phobos_colour_2008.jpg", 
            "photo": \000,
            "fk_planet_moon": 2
        }, { 
            "id": 2, 
            "name": "Io", 
            "radius": 1818.1, 
            "volume": 2.53, 
            "mass": 8.931, 
            "distance_from_planet": 421700, 
            "orbital_period": 1.769, 
            "surface_gravity": 1.796,
            "history": "driest known object in the Solar System", 
            "photo_link": "http://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Io_highest_resolution_true_color.jpg/260px-Io_highest_resolution_true_color.jpg", 
            "photo": \001,
            "fk_planet_moon": 3
        }]

## Moon [/api/moon/{id}]
A single Moon object with all its details

+ Parameters
    + id (required, int, `1`) ... int `id` of the Moon to perform action with. Has example value.

### Retrieve a Moon [GET]
+ Response 200 (application/json)

    + Header

    + Body

            { 
                "id": 1, 
                "name": "Phobos", 
                "radius": 11.26, 
                "volume": 5783.61, 
                "mass": 1.0659, 
                "distance_from_planet": 5826, 
                "orbital_period": .318, 
                "surface_gravity": 0.0057,
                "history": "named after the Greek god Phobos - the personfication of Horror", 
                "photo_link": "http://en.wikipedia.org/wiki/File:Phobos_colour_2008.jpg", 
                "photo": \000,
                "fk_planet_moon": 2
            }

+ Response 404 (application/json)

    + Header

    + Body
    
            { 
                "error": "Sorry. That Moon doesn't exist."
            }
            
# Group Planet Resources
## Planet Collection [/api/planet]
A list of all Planet objects
### List all Planets [GET]
+ Response 200 (application/json)

        [{ 
            "id": 1, 
            "name": "Jupiter", 
            "distance_from_sun": 483800000, 
            "composition": "H2, He, CH4, NH3, HD, C2H6, H2O", 
            "orbital_period": 4332.59, 
            "volume": 1.43, 
            "mass": 1.89, 
            "density": 1.3, 
            "surface_area": 6.14, 
            "semi_major_axis": 778547200, 
            "rings": 0, 
            "gravity": 3.70, 
            "length_of_day": 9, 
            "length_of_year": 12, 
            "surface_temperature": 440, 
            "atmosphere": "NH3, H2O, NH4SH", 
            "number_of_moons": 0, 
            "history": "largest planet in the Solar System", 
            "fk_star_planet": 7, 
            "photo_link": "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Jupiter_New_Horizons.jpg/260px-Jupiter_New_Horizons.jpg", 
            "photo": \000
        }, { 
            "id": 2, 
            "name": "Saturn", 
            "distance_from_sun": 890700000, 
            "composition": "H2, He, CH4, NH3, HD, C2H6", 
            "orbital_period": 10759.22, 
            "volume": 8.73, 
            "mass": 5.68, 
            "density": 0.687, 
            "surface_area": 4.27, 
            "semi_major_axis": 1433449370, 
            "rings": "Yes", 
            "gravity": 10.44, 
            "length_of_day": 10.39, 
            "length_of_year": 29, 
            "surface_temperature": 227, 
            "atmosphere": "H2, He", 
            "number_of_moons": 62, 
            "history": "named after the Roman god of agriculture", 
            "fk_star_planet": 8, 
            "photo_link": "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Saturn_Equinox_09212014.jpg/280px-Saturn_Equinox_09212014.jpg", 
            "photo": \001
        }]

## Planet [/api/planet/{id}]
A single Planet object with all its details

+ Parameters
    + id (required, int, `1`) ... int `id` of the Planet to perform action with. Has example value.

### Retrieve a Planet [GET]
+ Response 200 (application/json)

    + Header

    + Body

            { 
                "id": 1, 
                "name": "Jupiter", 
                "distance_from_sun": 483800000, 
                "composition": 7, 
                "orbital_period": 4332.59, 
                "volume": 1.43, 
                "mass": 1.89, 
                "density": 1.3, 
                "surface_area": 6.14, 
                "semi_major_axis": 778547200, 
                "rings": 0, 
                "gravity": 3.70, 
                "length_of_day": 9, 
                "length_of_year": 12, 
                "surface_temperature": 440, 
                "atmosphere": "NH3, H2O, NH4SH", 
                "number_of_moons": 0, 
                "history": "largest planet in the Solar System", 
                "fk_star_planet": 7, 
                "photo_link": "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Jupiter_New_Horizons.jpg/260px-Jupiter_New_Horizons.jpg", 
                "photo": \000
            }

+ Response 404 (application/json)

    + Header

    + Body
    
            { 
                "error": "Sorry. That Planet doesn't exist."
            }
            
# Group Star Resources
## Star Collection [/api/star]
A list of all Star objects
### List all Stars [GET]
+ Response 200 (application/json)

        [{ 
            "id": 1,
            "name": "Upsilon Andromedae"
            "mass": 1.27,
            "radius": 1.48,
            "spectral_type": "F8 V",
            "temperature": 6074,
            "luminosity": 3.57,
            "stellar_distance": 101,
            "parallax": 30.91,
            "planetary systems": 4,
            "fk_constellation_star": 2,
            "history": "located 44 light-years from Earth",
            "photo_link": "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/UAnd_planets.png/200px-UAnd_planets.png",
            "photo": \000
        }, { 
            "id": 2,
            "name": "Regulus"
            "mass": 3.8,
            "radius": 3.09,
            "spectral_type": "B7 V",
            "temperature": 12.46,
            "luminosity": 288,
            "stellar_distance": 127,
            "parallax": 41.14,
            "planetary systems": 9,
            "fk_constellation_star": 6,
            "history": "79 light years from earth",
            "photo_link": "http://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Leo_IAU.svg/250px-Leo_IAU.svg.png",
            "photo": \001
        }]

## Star [/api/star/{id}]
A single Star object with all its details

+ Parameters
    + id (required, int, `1`) ... int `id` of the Star to perform action with. Has example value.

### Retrieve a Star [GET]
+ Response 200 (application/json)

    + Header

    + Body

            { 
                "id": 1,
                "name": "Upsilon Andromedae"
                "mass": 1.27,
                "radius": 1.48,
                "spectral_type": "F8 V",
                "temperature": 6074,
                "luminosity": 3.57,
                "stellar_distance": 101,
                "parallax": 30.91,
                "planetary systems": 4,
                "fk_constellation_star": 2,
                "history": "located 44 light-years from Earth",
                "photo_link": "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/UAnd_planets.png/200px-UAnd_planets.png",
                "photo": \000
            }

+ Response 404 (application/json)

    + Header

    + Body
    
            { 
                "error": "Sorry. That Star doesn't exist."
            }