FORMAT: 1A

# StarLords
An API to access resources in our Universe database (https://github.com/sygmo/cs373-idb/)

# Group Constellation
Constellation related resources of the **Notes API**

## Constellation Collection [/api/constellation]
A list of all constellation objects
### List all Constellations [GET]
+ Response 200 (application/json)

        [{ 
                "id": 1, 
                "name": "Draco", 
                "meaning": "dragon", 
                "stars_with_planets": 19, 
                "fk_constellation_family": 3, 
                "history": "lies in the far northern sky. eighth-largest constellation", 
                "photo_link": "http://upload.wikimedia.org/wikipedia/commons/c/c3/DracoCC.jpg", 
                "photo": 000
            }, { 
                "id": 2, 
                "name": "Fornax", 
                "meaning": "chemical furnace", 
                "stars_with_planets": 7, 
                "fk_constellation_family": 4, 
                "history": "lies in the southern sky. is in the southern hemisphere", 
                "photo_link": "http://upload.wikimedia.org/wikipedia/commons/c/ce/Constellation_Fornax.jpg", 
                "photo": 101
        }]

## Constellation [/api/constellation/{id}]
A single Constellation object with all its details

+ Parameters
    + id (required, int, `1`) ... int `id` of the Constellation to perform action with. Has example value.

### Retrieve a Constellation [GET]
+ Response 200 (application/json)

    + Header

    + Body

            { 
                "id": 1, 
                "name": "Draco", 
                "meaning": "dragon", 
                "stars_with_planets": 19, 
                "fk_constellation_family": 3, 
                "history": "lies in the far northern sky. eighth-largest constellation", 
                "photo_link": "http://upload.wikimedia.org/wikipedia/commons/c/c3/DracoCC.jpg", 
                "photo": 000
            }

+ Response 404 (application/json)

    + Header

    + Body
    
            { 
                "error": "Sorry. That constellation doesn't exist."
            }

